-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE subscription_plans
-- SET "subscriptionFee" = 30
-- WHERE id = 'cdb86d0a-9144-495a-8a03-1c7ace793ddc';
