-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE badge SET "minVal" = 30 WHERE name = 'curious_collector' AND description = 'Users who have collected 30 red orbs in Sound Explorer';
