-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."game_settings" add column "createdAt" Timestamp
--  null default now();
