-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."game" add column "totalXpCoins" integer
--  not null default '0';
