-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE badge SET "minVal" = 20 WHERE name = 'beat_boxer_collector_1';
-- UPDATE badge SET "minVal" = 25  WHERE name = 'beat_boxer_collector_2';
-- UPDATE badge SET "minVal" = 30 WHERE name = 'beat_boxer_collector_3';
-- UPDATE badge SET "minVal" = 10 WHERE name = 'beat_boxer_combo_1';
-- UPDATE badge SET "minVal" = 15 WHERE name = 'beat_boxer_combo_2';
-- UPDATE badge SET "minVal" = 20 WHERE name = 'beat_boxer_combo_3';
