-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE badge SET metric = 'leaderboard_position' WHERE name = 'leaderboard_achiever_1';
-- UPDATE badge SET metric = 'leaderboard_position' WHERE name = 'leaderboard_achiever_2';
-- UPDATE badge SET metric = 'leaderboard_position' WHERE name = 'leaderboard_achiever_3';
