-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TRIGGER trigger_log_subscriptions_history_insert
-- AFTER INSERT
-- ON subscriptions
-- FOR EACH ROW EXECUTE PROCEDURE triggerLogSubscriptionsHistory();
