-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE subscription_plans
-- SET "priceId" = 'price_1MPLcCSJ1afwULmmy4xLDiEj', "productId" = 'prod_N9ewduBJ6pTsSg'
-- WHERE id = 'cdb86d0a-9144-495a-8a03-1c7ace793ddc';
