-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO subscription_status (status, description) VALUES ('active', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('cancelled', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('archived', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('payment_pending', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('blocked', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('trial_period', NULL);
-- INSERT INTO subscription_status (status, description) VALUES ('trial_expired', NULL);
