-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TRIGGER trigger_log_game_settings_update
-- AFTER UPDATE OF configuration
-- ON game_settings
-- FOR EACH ROW EXECUTE PROCEDURE triggerLogGameSettingsUpdate();
