-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."patient" add column "totalCoins" integer
--  not null default '0';
