-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE badge SET metric = 'patient_total_activity_count' WHERE name = 'frequent_flyer_100';
