-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE badge SET "minVal" = 20 WHERE name = 'sound_explorer_collector_1';
-- UPDATE badge SET "minVal" = 50 WHERE name = 'sound_explorer_collector_2';
-- UPDATE badge SET "minVal" = 70 WHERE name = 'sound_explorer_collector_3';
-- UPDATE badge SET "minVal" = 10 WHERE name = 'sound_explorer_combo_1';
-- UPDATE badge SET "minVal" = 15 WHERE name = 'sound_explorer_combo_2';
-- UPDATE badge SET "minVal" = 20 WHERE name = 'sound_explorer_combo_3';
